import { Chapter } from './types';

export const CHAPTERS: Chapter[] = [
  {
    id: 'childhood',
    index: 1,
    title: 'CHILDHOOD',
    subtitle: 'Piggy banks & Diwali money',
    ageRange: 'Age 8 — 14',
    endAge: 14,
    landscape: {
      sky: ['#FFB36B', '#FF8C42'],
      ground: '#7CB342',
      accent: '#A0522D',
      name: 'VILLAGE',
    },
    scenarios: [
      {
        id: 'c1s1',
        age: 8,
        title: 'BIRTHDAY MONEY SPLIT',
        prompt: 'Dadi gives you Rs 500 for your birthday. Next week is the book fair, and your class raffle costs Rs 100 for a chance at a pizza party.',
        scene: 'home',
        advanceYears: 1,
        choices: [
          {
            id: 'comics',
            label: 'BUY THE COMICS',
            hint: 'Read them now, save a little',
            delta: { cash: -450, happiness: 12 },
            consequenceText: 'You buy the comic series and enjoy it right away. Friends ask to borrow them, but your savings stay small.',
            lesson: 'Spending can be satisfying, and sometimes the right choice is the one that feels worth it now.',
            concept: 'Delayed Gratification',
          },
          {
            id: 'raffle',
            label: 'ENTER THE RAFFLE',
            hint: 'Small gamble, big social upside',
            delta: { cash: -100, savings: 400, happiness: 6 },
            consequenceText: 'You put Rs 100 in the raffle and save the rest. Winning would be a huge social moment; losing means you miss both the pizza party AND the comics.',
            lesson: 'Some choices are about chance, not correctness. Risk can feel smart and still lose. ',
            concept: 'Risk vs Certainty',
          },
          {
            id: 'save_all',
            label: 'SAVE THE FULL Rs 500',
            hint: 'Big number, no treats',
            delta: { savings: 500, happiness: 2, knowledge: 5 },
            consequenceText: 'You keep all Rs 500 safe. You lose the comics and the raffle, and your friends may say you never buy anything for yourself.',
            lesson: 'Saving is powerful, but it is also a choice with its own emotional cost.',
            concept: 'Savings Basics',
          },
        ],
      },
      {
        id: 'c1s2',
        age: 7,
        title: 'PIGGY BANK VS THE FRIEND’S DARE',
        prompt: 'Your best friend got a glow-in-the-dark yo-yo and says you cannot play with the group unless you get one too. You have Rs 300 saved, but you never wanted one until today.',
        scene: 'school',
        advanceYears: 1,
        choices: [
          {
            id: 'break_piggy',
            label: 'BREAK THE PIGGY & BUY IT',
            hint: 'Fit in now, spend on pressure',
            delta: { cash: -150, happiness: 10 },
            consequenceText: 'You buy the yo-yo and join the group instantly. It is fun for a while, but you spent money on something you did not really want.',
            lesson: 'Buying to fit in can feel good in the moment, but it is worth noticing whether the want was yours or the pressure’s.',
            concept: 'Needs vs Wants',
          },
          {
            id: 'talk',
            label: 'ASK WHY IT MATTERS',
            hint: 'Honest talk, outcome uncertain',
            delta: { happiness: 4, knowledge: 8 },
            consequenceText: 'You ask your friend why the yo-yo is so important. The result is uncertain — maybe the friend backs down, maybe the group stays distant for a few days.',
            lesson: 'The most thoughtful choice is not always the safest one. Honesty can still have an unpredictable social cost.',
            concept: 'Friendship',
          },
          {
            id: 'cheaper',
            label: 'BUY A Rs 50 YO-YO',
            hint: 'Less money, lower quality',
            delta: { cash: -50, happiness: 6 },
            consequenceText: 'You spend less and still join the group, but the yo-yo is cheaper and your friend may notice the difference.',
            lesson: 'Compromise can reduce cost, but it does not always solve the underlying pressure.',
            concept: 'Needs vs Wants',
          },
        ],
      },
      {
        id: 'c1s3',
        age: 11,
        title: 'REPORT CARD REWARD',
        prompt: 'You scored well this term. Papa gives you Rs 1,000 and says, “Use it however you want.” Your sibling spent theirs on a toy that broke in a week.',
        scene: 'home',
        advanceYears: 1,
        choices: [
          {
            id: 'spend',
            label: 'SPEND IT ALL',
            hint: 'Fun now, risk later',
            delta: { cash: -1000, happiness: 16 },
            consequenceText: 'You spend all Rs 1,000 on something fun and feel great now. The item may break or lose appeal quickly, just like your sibling’s toy.',
            lesson: 'A reward can feel wonderful, but it can also disappear fast. That uncertainty is part of the choice.',
            concept: 'Savings vs Spending',
          },
          {
            id: 'save_all',
            label: 'SAVE THE FULL Rs 1,000',
            hint: 'Papa proud, no spotlight',
            delta: { savings: 1000, happiness: 3, knowledge: 8 },
            consequenceText: 'You save the entire amount and tell Papa. He is proud, but it creates pressure to always be the “saver.”',
            lesson: 'Approval is real, but it can also create expectations that cost you later.',
            concept: 'Parental Approval',
          },
          {
            id: 'split',
            label: 'SPEND Rs 400, SAVE Rs 600',
            hint: 'Balanced, quiet choice',
            delta: { cash: -400, savings: 600, happiness: 8 },
            consequenceText: 'You spend a little and save the rest. There is no big praise, but you avoid the extremes of either extreme choice.',
            lesson: 'Balanced choices may not feel dramatic, but they are often the most sustainable.',
            concept: 'Savings Basics',
          },
        ],
      },
      {
        id: 'c1s4',
        age: 9,
        title: 'THE BORROWED TOY PROBLEM',
        prompt: 'A friend lent you a handheld game and it got a small scratch at your house. It still works, but your friend has not noticed yet. You have Rs 250 saved.',
        scene: 'home',
        advanceYears: 1,
        choices: [
          {
            id: 'cover',
            label: 'BUY A STICKER KIT',
            hint: 'Hide the scratch for Rs 80',
            delta: { cash: -80, happiness: 5 },
            consequenceText: 'You buy sticker kit and cover the scratch. If your friend never notices, you avoided awkwardness; if they do, it may look like you tried to hide it.',
            lesson: 'Money can fix the surface of a problem, but it cannot buy certainty about how others will react.',
            concept: 'Friendship',
          },
          {
            id: 'honest',
            label: 'TELL THE TRUTH',
            hint: 'Offer Rs 80 for repair',
            delta: { happiness: 6, knowledge: 6 },
            consequenceText: 'You tell your friend honestly and offer Rs 80 toward a repair. The reaction is uncertain — honesty may be respected, or it may still feel awkward.',
            lesson: 'Honesty is a strong choice, but it does not guarantee a perfect result.',
            concept: 'Trust',
          },
          {
            id: 'ignore',
            label: 'SAY NOTHING',
            hint: 'Save money, hope for the best',
            delta: { happiness: 2 },
            consequenceText: 'You keep the Rs 80 and stay quiet. If your friend never notices, you saved money; if they do, it may look careless.',
            lesson: 'Not spending money can still be a risk when it means avoiding responsibility.',
            concept: 'Needs vs Wants',
          },
        ],
      },
      {
        id: 'c1s5',
        age: 10,
        title: 'THE FESTIVAL FIRECRACKER BUDGET',
        prompt: 'It’s Diwali and you have Rs 500 for firecrackers. The shop also sells a sealed Rs 100 lucky box — it might be great, or it might be mostly duds.',
        scene: 'home',
        advanceYears: 1,
        choices: [
          {
            id: 'regular',
            label: 'BUY Rs 500 OF REGULAR CRACKERS',
            hint: 'Predictable fun',
            delta: { cash: -500, happiness: 10 },
            consequenceText: 'You buy clearly-priced crackers and know exactly what you will get. The festival is still bright, but you never know if the lucky box would have been better.',
            lesson: 'Certainty is valuable. A sure outcome can be better than a bigger but riskier one.',
            concept: 'Risk Sizing',
          },
          {
            id: 'one_lucky',
            label: 'BUY 1 LUCKY BOX + Rs 400 REGULAR',
            hint: 'Small gamble, limited risk',
            delta: { cash: -500, happiness: 12 },
            consequenceText: 'You mix one lucky box with regular crackers. The gamble is contained — if it is a letdown, only Rs 100 is at risk.',
            lesson: 'A small, controlled gamble can make spending more exciting without risking everything.',
            concept: 'Needs vs Wants',
          },
          {
            id: 'three_lucky',
            label: 'BUY 3 LUCKY BOXES + Rs 200 REGULAR',
            hint: 'Bigger gamble, bigger risk',
            delta: { cash: -500, happiness: 14 },
            consequenceText: 'You choose three lucky boxes for more excitement. If luck holds, it is great; if not, you miss out on a stronger regular mix.',
            lesson: 'Risk exposure matters. The same gamble feels different when you bet more of your budget on it.',
            concept: 'Risk Sizing',
          },
        ],
      },
      {
        id: 'c1s6',
        age: 9,
        title: 'CANTEEN CHANGE MIX-UP',
        prompt: 'You buy a samosa and juice for Rs 37 and give the aunty Rs 50. She hands back Rs 23. Did she make a mistake?',
        scene: 'school',
        advanceYears: 1,
        choices: [
          {
            id: 'return',
            label: 'POINT OUT THE EXTRA Rs 10',
            hint: 'Honest, smaller pocket',
            delta: { cash: -10, happiness: 4 },
            consequenceText: 'You return the extra Rs 10. The aunty thanks you and may trust you more, even though you gave back money immediately.',
            lesson: 'Doing the right thing can cost you money, and that is part of what makes honesty meaningful.',
            concept: 'Honesty with Money',
          },
          {
            id: 'keep',
            label: 'KEEP QUIET AND WALK AWAY',
            hint: 'Small gain, hidden risk',
            delta: { cash: 10, happiness: 6 },
            consequenceText: 'You keep the money and walk away. It feels like a win, but there is always a chance the aunty will check later and remember your order.',
            lesson: 'A small windfall can feel good, but it also carries a risk if it comes from someone else’s mistake.',
            concept: 'Ethics',
          },
          {
            id: 'not_check',
            label: 'DON’T CHECK THE CHANGE',
            hint: 'Stay uncertain',
            delta: { happiness: 2 },
            consequenceText: 'You pocket the money without checking. You may have taken the right amount, or you may have a secret extra — and you won’t know.',
            lesson: 'Sometimes the hardest part of a money decision is not what you do, but whether you notice what has happened.',
            concept: 'Attention to Detail',
          },
        ],
      },
    ],
  },
  {
    id: 'teenage',
    index: 2,
    title: 'TEENAGE',
    subtitle: 'Peer pressure & first paychecks',
    ageRange: 'Age 14 — 19',
    endAge: 19,
    landscape: {
      sky: ['#7FBFFF', '#3498DB'],
      ground: '#5D6D7E',
      accent: '#C0392B',
      name: 'NEIGHBOURHOOD',
    },
    scenarios: [
      {
        id: 'c2s1',
        age: 15,
        title: 'THE ALLOWANCE SWITCH',
        prompt: 'Papa switches you from on-request cash to a flat Rs 250/month. You have stationery/data needs and Friday hangouts with friends.',
        scene: 'school',
        advanceYears: 1,
        choices: [
          {
            id: 'full_hangouts',
            label: 'SPEND Rs 120 ON HANGOUTS',
            hint: 'Social calendar stays full',
            delta: { cash: -120, happiness: 14, knowledge: 6 },
            consequenceText: 'You keep all Friday hangouts and rely on the rest for stationery. The month feels fun, but the rest of your budget is tight.',
            lesson: 'A comfortable routine can still be risky when your remaining money has little room for surprises.',
            concept: 'Budgeting Under Uncertainty',
          },
          {
            id: 'skip_one',
            label: 'SKIP ONE FRIDAY',
            hint: 'Save for the unknown',
            delta: { cash: -90, savings: 30, happiness: 8 },
            consequenceText: 'You miss a hangout and keep a little buffer. It feels like money saved for “maybe later”, but that buffer may never be needed.',
            lesson: 'A safer choice can also feel like a real sacrifice if the risk never happens.',
            concept: 'Fixed vs Variable Costs',
          },
          {
            id: 'borrow',
            label: 'KEEP ALL FRIDAYS, BORROW SUPPLIES',
            hint: 'Social life stays intact, if it works',
            delta: { cash: -120, happiness: 12, knowledge: 10 },
            consequenceText: 'You keep the hangouts and try to borrow stationery. If friends help, you win; if not, you are left with the same tight budget and extra effort.',
            lesson: 'A clever plan is only as good as the people around you. Some choices depend on luck and cooperation too.',
            concept: 'Opportunity Cost',
          },
        ],
      },
      {
        id: 'c2s2',
        age: 17,
        title: 'THE COACHING ADVANCE',
        prompt: 'A coaching institute asks for Rs 2,500 advance to lock your seat. A great calculator is also available for Rs 900 only this week.',
        scene: 'school',
        advanceYears: 1,
        choices: [
          {
            id: 'full_commit',
            label: 'PAY ADVANCE & BUY CALCULATOR',
            hint: 'Seat secured, calculator bought',
            delta: { cash: -3400, savings: 600, happiness: 10 },
            consequenceText: 'You pay the advance and buy the calculator. Your seat is secure, but almost nothing is left for the remainder of the fee.',
            lesson: 'When one cost is known and another is uncertain, you can still end up exposed if you commit too much too soon.',
            concept: 'Budgeting Under Uncertainty',
          },
          {
            id: 'advance_only',
            label: 'PAY ADVANCE, SKIP CALCULATOR',
            hint: 'Reserve cash, miss the deal',
            delta: { cash: -2500, savings: 1500, happiness: 6 },
            consequenceText: 'You secure the seat and keep a buffer. The calculator deal is gone, and you may regret missing the one-time bargain.',
            lesson: 'Safety can cost you good opportunities. A buffer is useful, but not if it means losing a clearly valuable item.',
            concept: 'Opportunity Cost',
          },
          {
            id: 'partial',
            label: 'PAY Rs 2,000, BUY CALCULATOR',
            hint: 'Split exposure, limited comfort',
            delta: { cash: -3100, savings: 900, happiness: 8 },
            consequenceText: 'You pay most of the advance and still buy the calculator. Neither cost is fully covered, leaving you modestly protected but also underexposed on both.',
            lesson: 'Partial protection is a real strategy, but it is only good if you accept that you are not fully safe on either side.',
            concept: 'Reserve Funds',
          },
        ],
      },
      {
        id: 'c2s3',
        age: 16,
        title: 'THE GROUP OUTING GIFT PRESSURE',
        prompt: 'Friends are chipping in for a senior gift. You have Rs 350 set aside for an exam book, and one friend loudly says they are paying Rs 600.',
        scene: 'street',
        advanceYears: 1,
        choices: [
          {
            id: 'full_amount',
            label: 'PUT IN Rs 350',
            hint: 'Join the group, skip the book',
            delta: { cash: -350, happiness: 10 },
            consequenceText: 'You contribute your full amount and stay part of the group. Your gift is lower than some, and you may wonder if people notice later.',
            lesson: 'Being part of the group often costs money, even when you do not want to overspend.',
            concept: 'Social Spending',
          },
          {
            id: 'partial_amount',
            label: 'PUT IN Rs 150, SAVE Rs 200',
            hint: 'Partial participation',
            delta: { cash: -150, savings: 200, happiness: 6 },
            consequenceText: 'You give less and keep money for your book. Some friends may respect the choice, and some may still feel you did not fully participate.',
            lesson: 'Honest budgeting can protect your goals, but it may also create social uncertainty.',
            concept: 'Peer Pressure',
          },
          {
            id: 'skip_gift',
            label: 'SKIP THE GIFT, GIVE A NOTE',
            hint: 'Protect your goal, leave the group',
            delta: { happiness: 4, savings: 350 },
            consequenceText: 'You skip the shared gift and give something small instead. You keep your exam book money, but you are not part of the group presentation.',
            lesson: 'Protecting your own goal can also mean choosing a different kind of social gesture.',
            concept: 'Opportunity Cost',
          },
        ],
      },
      {
        id: 'c2s4',
        age: 15,
        title: 'THE CAFÉ SWITCH',
        prompt: 'You and friends planned tea, but two friends want to switch to a café with Rs 90 shakes. You only have Rs 20.',
        scene: 'street',
        advanceYears: 1,
        choices: [
          {
            id: 'go_along',
            label: 'GO ALONG AND BE HONEST',
            hint: 'No hiding, maybe awkward',
            delta: { happiness: 6, knowledge: 8 },
            consequenceText: 'You tell your friends you only have Rs 20 and may just sit with them. The reaction is unknown — some may cover you, some may keep ordering.',
            lesson: 'Honesty in the moment can be uncomfortable, but it is often better than pretending you can afford it.',
            concept: 'Peer Pressure',
          },
          {
            id: 'skip',
            label: 'SKIP THE CAFE, STAY FOR FRIENDS',
            hint: 'No spending, no explanation',
            delta: { happiness: 4 },
            consequenceText: 'You stay with the group without spending. You avoid the awkward money conversation, but you also miss the main shared activity.',
            lesson: 'Avoiding a problem now can make it repeat later if the group never knows your real limit.',
            concept: 'Budgeting',
          },
          {
            id: 'suggest_tea',
            label: 'SUGGEST STICKING TO TEA',
            hint: 'Try to redirect the group',
            delta: { happiness: 5, knowledge: 6 },
            consequenceText: 'You suggest the original tea stall. It may work if someone agrees, or it may leave you having to choose again.',
            lesson: 'Sometimes the best choice is to try to change the plan before the cost becomes real.',
            concept: 'Social Spending',
          },
        ],
      },
      {
        id: 'c2s5',
        age: 16,
        title: 'THE TUITION CENTER JOB',
        prompt: 'The tuition center offers you a front desk job for Rs 1,500/month, but it runs at the same time as your regular study group.',
        scene: 'school',
        advanceYears: 1,
        choices: [
          {
            id: 'take_job',
            label: 'TAKE THE JOB, STUDY LATER',
            hint: 'Earn first, study later',
            delta: { cash: 1500, knowledge: 6, happiness: 8 },
            consequenceText: 'You earn Rs 1,500 and miss the study group. Whether your grades stay strong is uncertain, but your money is real.',
            lesson: 'Income is important, but so is the time it costs you. The trade-off is not always obvious at first.',
            concept: 'Opportunity Cost',
          },
          {
            id: 'skip_job',
            label: 'SKIP THE JOB, KEEP STUDYING',
            hint: 'No income, same routine',
            delta: { happiness: 4, knowledge: 10 },
            consequenceText: 'You keep your study routine and miss the extra income. The money never appears, even though your schedule stays comfortable.',
            lesson: 'Choosing not to earn is still a decision with a real cost.',
            concept: 'Part-Time Earning',
          },
          {
            id: 'negotiate',
            label: 'ASK FOR FEWER HOURS',
            hint: 'Try for balance',
            delta: { cash: 800, happiness: 6, knowledge: 8 },
            consequenceText: 'You try to work alternate days for Rs 800. The center may accept or may decide they need a full-time helper, and you may be back to the original choice.',
            lesson: 'Compromise can be good, but it depends on whether the other side is willing to meet you.',
            concept: 'Time vs Money',
          },
        ],
      },
    ],
  },
  {
    id: 'college',
    index: 3,
    title: 'COLLEGE',
    subtitle: 'Loans, hostels & first jobs',
    ageRange: 'Age 19 — 24',
    endAge: 24,
    landscape: {
      sky: ['#A29BFE', '#6C5CE7'],
      ground: '#4A4A6A',
      accent: '#F1C40F',
      name: 'CAMPUS',
    },
    scenarios: [
      {
        id: 'c3s1',
        age: 19,
        title: 'THE LOAN TENURE TRAP',
        prompt: 'A Rs 6,00,000 education loan at 10.5% is ready. The bank wants your repayment tenure now, but you do not know your future salary.',
        scene: 'college',
        advanceYears: 2,
        choices: [
          {
            id: 'short_tenure',
            label: '5-YEAR TENURE',
            hint: 'Less interest, higher EMI',
            delta: { debt: 600000, happiness: 6, knowledge: 12 },
            consequenceText: 'You choose the short tenure. Your total interest is lower, but the EMI could take a large share of your future salary.',
            lesson: 'A lower cost today can become a burden if your future income does not keep up.',
            concept: 'Loan Trade-offs',
          },
          {
            id: 'long_tenure',
            label: '10-YEAR TENURE',
            hint: 'Lower EMI, more interest',
            delta: { debt: 600000, happiness: 6, knowledge: 10 },
            consequenceText: 'You choose the long tenure. The monthly payment is easier, but you pay much more interest over time.',
            lesson: 'More manageable payments can still cost you heavily in the long run.',
            concept: 'Loan Interest',
          },
          {
            id: 'long_plus_prepay',
            label: 'LONG TENURE + PREPAY PLAN',
            hint: 'Best if you follow through',
            delta: { debt: 600000, happiness: 8, knowledge: 14 },
            consequenceText: 'You take the long tenure and plan to prepay later. It is a good plan only if you actually save enough to follow it.',
            lesson: 'The smartest plan is only as good as your future discipline.',
            concept: 'Loan Planning',
          },
        ],
      },
      {
        id: 'c3s2',
        age: 21,
        title: 'THE UPI TRAP',
        prompt: 'You have Rs 8,000/month allowance. A UPI history check shows Rs 4,200 has already disappeared in small taps, and only Rs 1,200 is left for 10 days.',
        scene: 'college',
        advanceYears: 1,
        choices: [
          {
            id: 'zero_spend',
            label: 'SPEND NOTHING FOR 10 DAYS',
            hint: 'Tight but safe',
            delta: { happiness: 2, knowledge: 8 },
            consequenceText: 'You stop discretionary spending for the rest of the month. The Rs 1,200 may stretch, but the social pressure to buy can be hard to resist.',
            lesson: 'A strict rule can work, but it is only as strong as your willpower.',
            concept: 'Invisible Spending',
          },
          {
            id: 'daily_cap',
            label: 'SET Rs 120/DAY CAP',
            hint: 'Controlled, no buffer',
            delta: { happiness: 4, knowledge: 10 },
            consequenceText: 'You limit yourself to Rs 120 per day. It is more sustainable than zero spending, but there is no room left for surprises.',
            lesson: 'A budget needs rules and also a little room for real life.',
            concept: 'Budgeting',
          },
          {
            id: 'ask_parents',
            label: 'ASK PARENTS FOR A TOP-UP',
            hint: 'Relief if they agree',
            delta: { happiness: 6, knowledge: 6 },
            consequenceText: 'You ask for help. The answer may be yes or no; the uncertainty is real and may feel worse than simply tightening your budget.',
            lesson: 'Asking for help is valid, but it does not guarantee the outcome you want.',
            concept: 'Financial Communication',
          },
        ],
      },
      {
        id: 'c3s3',
        age: 23,
        title: 'FIRST INTERNSHIP STIPEND',
        prompt: 'Your 3-month internship paid Rs 60,000. Friends are already booking flights. Your gut says save.',
        scene: 'street',
        advanceYears: 1,
        choices: [
          {
            id: 'spend',
            label: 'PARTY WITH FRIENDS',
            hint: 'Memories now, balance later',
            delta: { cash: -60000, happiness: 20 },
            consequenceText: 'You spend the stipend on trips and gadgets. It feels great now, but the money is gone before your next paycheck.',
            lesson: 'A windfall is a test of your habits. Spending everything teaches the wrong lesson sooner than any budget number.',
            concept: 'Windfall Management',
          },
          {
            id: 'emergency',
            label: 'BUILD EMERGENCY FUND',
            hint: 'Safety first',
            delta: { savings: 60000, happiness: 6, knowledge: 14 },
            setFlags: ['has_emergency_fund'],
            consequenceText: 'You set the money aside in a liquid fund. You now have a true buffer for unexpected needs.',
            lesson: 'Money you save for a real emergency is often worth more than the toys you buy today.',
            concept: 'Emergency Fund',
          },
          {
            id: 'invest',
            label: 'INVEST IN INDEX FUNDS',
            hint: 'Long-term growth',
            delta: { savings: 60000, happiness: 4, knowledge: 18 },
            setFlags: ['has_mutual_fund'],
            futureAge: 24,
            futureDelta: { savings: 12000 },
            futureMessage: 'Your index fund returned 20% in one year — Rs 12,000 extra added silently.',
            consequenceText: 'You invest Rs 60,000 in a low-cost index fund. The market may go up or down, but over time this is a smart way to build wealth.',
            lesson: 'Investing is not a guarantee, but over time it beats keeping cash idle.',
            concept: 'Compound Interest',
          },
        ],
      },
    ],
  },
  {
    id: 'early_career',
    index: 4,
    title: 'EARLY CAREER',
    subtitle: 'First salaries & investing choices',
    ageRange: 'Age 24 — 30',
    endAge: 30,
    landscape: {
      sky: ['#0F3460', '#16213E'],
      ground: '#3D3D5C',
      accent: '#2ECC71',
      name: 'METRO',
    },
    scenarios: [
      {
        id: 'c4s1',
        age: 25,
        title: 'THE Rs 89,000 DECISION',
        prompt:
          "Your year-end bonus just landed — Rs 89,000, separate from your salary. Your SIP is already running on its own. This money has no plan yet. First time you've had enough to actually treat this as an investment decision, not just a spending one.",
        scene: 'home',
        advanceYears: 1,
        skipCompound: true,
        terms: [
          {
            name: 'Fixed Deposit (FD)',
            definition:
              "You give the bank your money for a fixed time, and they pay it back with a bit extra on top — at a rate that's locked in from day one.",
          },
          {
            name: 'Equity Mutual Fund',
            definition:
              'Your money goes into the stock market, spread across many companies, instead of you picking stocks yourself.',
          },
          {
            name: 'STP (Systematic Transfer Plan)',
            definition:
              'A staggered way into the stock market — instead of investing everything on one day, a fixed amount moves in automatically every month.',
          },
          {
            name: 'PPF (Public Provident Fund)',
            definition:
              'A government-backed savings scheme, very safe, tax-free returns — but your money is locked in for 15 years.',
          },
        ],
        choices: [
          {
            id: 'fd',
            label: 'PUT IT IN A FIXED DEPOSIT',
            hint: 'Guaranteed, predictable growth',
            delta: { cash: -89000, savings: 95230, knowledge: 8 },
            consequenceText:
              'You locked your Rs 89,000 into a fixed deposit at 7% for a year. No drama, no checking the news — it just sat there, growing slowly.',
            lesson:
              "FDs won't make you rich, but they won't surprise you either. Guaranteed growth has a real cost: it's slower than what the market could've done.",
            concept: 'Fixed Deposit (FD)',
            accelCaptions: {
              cash: 'You moved Rs 89,000 out of cash and into a locked deposit.',
              savings: 'Your FD earned Rs 6,230 in interest over the year.',
              knowledge:
                "Knowledge +8. You understand 'Fixed Deposits' a little better now.",
            },
          },
          {
            id: 'equity_lumpsum',
            label: 'LUMP SUM INTO EQUITY MUTUAL FUND',
            hint: "Higher growth potential, full amount exposed to today's price",
            delta: { cash: -89000, savings: 98700, knowledge: 8 },
            consequenceText:
              'You put the full Rs 89,000 into an equity fund on day one. The market dipped 8% in month two before recovering — for a few weeks, your Rs 89,000 was worth less than Rs 82,000 on paper.',
            lesson:
              "It worked out this time — but for a while, you were down. That dip was the real cost of investing the full amount on a single day. Same bet, different timing, and the ride could've gone the other way.",
            concept: 'Equity Mutual Fund',
            accelCaptions: {
              cash: 'You moved Rs 89,000 out of cash into the market.',
              savings:
                'After a rocky few months, your investment grew to Rs 98,700 by year-end.',
              knowledge:
                "Knowledge +8. You understand 'Equity Mutual Funds' a little better now.",
            },
          },
          {
            id: 'stp',
            label: 'STP INTO EQUITY OVER 6-12 MONTHS',
            hint: 'Smooths out the timing risk of going all-in today',
            delta: { cash: -89000, savings: 96100, knowledge: 8 },
            consequenceText:
              'You parked the Rs 89,000 in a liquid fund and let Rs 9,000 move into equity every month. By the time the market dipped in month two, only Rs 18,000 was exposed — the rest was still safely parked.',
            lesson:
              "You paid a small price in upside for a smoother ride. In a year the market mostly rises, going all-in usually wins. In a year it dips early, staggering in usually wins. You can't know which year it'll be in advance.",
            concept: 'STP (Systematic Transfer Plan)',
            accelCaptions: {
              cash:
                'You moved Rs 89,000 out of cash into a liquid fund, then staggered it into equity.',
              savings:
                'By year-end, smoother entry left you with Rs 96,100 — slightly less than going all-in, since the market mostly rose this year.',
              knowledge:
                "Knowledge +8. You understand 'STP (Systematic Transfer Plan)' a little better now.",
            },
          },
          {
            id: 'ppf',
            label: 'PUT IT IN PPF',
            hint: 'Tax-free and safest, but locked in for 15 years',
            delta: { cash: -89000, savings: 95319, knowledge: 8 },
            consequenceText:
              "You put the full Rs 89,000 into your PPF account. It's now locked in, quietly earning tax-free interest, completely untouchable for the next 15 years.",
            lesson:
              "Safe and tax-free — but for the next 15 years, this money can't help with anything else, even a real emergency. Long-term security has a real cost: zero flexibility.",
            concept: 'PPF (Public Provident Fund)',
            accelCaptions: {
              cash: 'You moved Rs 89,000 out of cash into your PPF account.',
              savings: 'Your PPF balance grew by Rs 6,319 this year, tax-free.',
              knowledge:
                "Knowledge +8. You understand 'PPF (Public Provident Fund)' a little better now.",
            },
          },
        ],
      },
    ],
  },
];

export const ALL_FLAGS: { key: string; positive: boolean; label: string }[] = [
  { key: 'saved_first_money', positive: true, label: 'Saved your first money' },
  { key: 'has_bank_account', positive: true, label: 'Opened a bank account' },
  { key: 'has_savings_habit', positive: true, label: 'Built a savings habit' },
  { key: 'entrepreneur_seed', positive: true, label: 'Earned your first profit' },
  { key: 'knows_value_of_money', positive: true, label: 'Learned to earn before spending' },
  { key: 'knows_upi_safety', positive: true, label: 'UPI safety expert' },
  { key: 'scammed_once', positive: false, label: 'Got scammed once' },
  { key: 'started_early_sip', positive: true, label: 'Started SIP at 18' },
  { key: 'has_education_loan', positive: false, label: 'Carrying education loan' },
  { key: 'scholarship_winner', positive: true, label: 'Scholarship winner' },
  { key: 'has_credit_debt', positive: false, label: 'Stuck in credit card debt' },
  { key: 'good_credit_score', positive: true, label: 'Built credit score' },
  { key: 'has_emergency_fund', positive: true, label: 'Has emergency fund' },
  { key: 'has_mutual_fund', positive: true, label: 'Invests in mutual funds' },
  { key: 'civic_minded', positive: true, label: 'Civic-minded citizen' },
];
